/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard.index'
import { Route as DashboardTripsImport } from './routes/dashboard.trips'
import { Route as DashboardSettingsImport } from './routes/dashboard.settings'
import { Route as DashboardMapImport } from './routes/dashboard.map'
import { Route as DashboardDevicesImport } from './routes/dashboard.devices'
import { Route as DashboardAlertsImport } from './routes/dashboard.alerts'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTripsRoute = DashboardTripsImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardMapRoute = DashboardMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDevicesRoute = DashboardDevicesImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAlertsRoute = DashboardAlertsImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/trips': {
      id: '/dashboard/trips'
      path: '/trips'
      fullPath: '/dashboard/trips'
      preLoaderRoute: typeof DashboardTripsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTripsRoute: typeof DashboardTripsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTripsRoute: DashboardTripsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/devices'
    | '/dashboard/map'
    | '/dashboard/settings'
    | '/dashboard/trips'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/alerts'
    | '/dashboard/devices'
    | '/dashboard/map'
    | '/dashboard/settings'
    | '/dashboard/trips'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/devices'
    | '/dashboard/map'
    | '/dashboard/settings'
    | '/dashboard/trips'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/alerts",
        "/dashboard/devices",
        "/dashboard/map",
        "/dashboard/settings",
        "/dashboard/trips",
        "/dashboard/"
      ]
    },
    "/dashboard/alerts": {
      "filePath": "dashboard.alerts.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/devices": {
      "filePath": "dashboard.devices.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/map": {
      "filePath": "dashboard.map.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings": {
      "filePath": "dashboard.settings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/trips": {
      "filePath": "dashboard.trips.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard.index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
